name: tts_app
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.12.2=hca03da5_0
  - expat=2.7.3=h50f4ffc_4
  - libcxx=20.1.8=hd7fd590_1
  - libexpat=2.7.3=h50f4ffc_4
  - libffi=3.4.4=hca03da5_1
  - libzlib=1.3.1=h5f15de7_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.18=h9b4081a_0
  - pip=25.3=pyhc872135_0
  - python=3.11.14=hf701271_0
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py311hca03da5_0
  - sqlite=3.51.0=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - wheel=0.45.1=py311hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - addict==2.4.0
      - aiofiles==24.1.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.12.0
      - attrs==25.4.0
      - audioread==3.1.0
      - babel==2.17.0
      - blis==1.3.3
      - brotli==1.2.0
      - catalogue==2.0.10
      - certifi==2025.11.12
      - cffi==2.0.0
      - cfgv==3.5.0
      - charset-normalizer==3.4.4
      - chatterbox-tts==0.1.6
      - click==8.3.1
      - cloudpathlib==0.23.0
      - confection==0.1.5
      - conformer==0.3.2
      - csvw==3.7.0
      - curated-tokenizers==0.0.9
      - curated-transformers==0.1.1
      - cymem==2.0.13
      - decorator==5.2.1
      - deprecated==1.3.1
      - diffusers==0.29.0
      - distlib==0.4.0
      - dlinfo==2.0.0
      - docopt==0.6.2
      - einops==0.8.1
      - espeakng-loader==0.2.4
      - fastapi==0.127.1
      - ffmpy==1.0.0
      - filelock==3.20.1
      - fsspec==2025.12.0
      - future==1.0.0
      - gradio==5.44.1
      - gradio-client==1.12.1
      - groovy==0.1.2
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - identify==2.6.15
      - idna==3.11
      - importlib-metadata==8.7.1
      - isodate==0.7.2
      - jaconv==0.4.1
      - jinja2==3.1.6
      - joblib==1.5.3
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kokoro==0.9.4
      - language-tags==1.2.0
      - lazy-loader==0.4
      - librosa==0.11.0
      - llvmlite==0.46.0
      - loguru==0.7.3
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - mdurl==0.1.2
      - misaki==0.9.4
      - ml-dtypes==0.5.4
      - mpmath==1.3.0
      - msgpack==1.1.2
      - murmurhash==1.0.15
      - natsort==8.4.0
      - networkx==3.6.1
      - nodeenv==1.10.0
      - num2words==0.5.14
      - numba==0.63.1
      - numpy==1.25.2
      - omegaconf==2.3.0
      - onnx==1.20.0
      - orjson==3.11.5
      - packaging==25.0
      - pandas==2.3.3
      - phonemizer-fork==3.3.2
      - pillow==11.3.0
      - platformdirs==4.5.1
      - pooch==1.8.2
      - pre-commit==4.5.1
      - preshed==3.0.12
      - protobuf==6.33.2
      - pycparser==2.23
      - pydantic==2.11.10
      - pydantic-core==2.33.2
      - pydub==0.25.1
      - pygments==2.19.2
      - pykakasi==2.3.0
      - pyloudnorm==0.1.1
      - pyparsing==3.3.1
      - pypdf2==3.0.1
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.21
      - pytz==2025.2
      - pyyaml==6.0.3
      - rdflib==7.5.0
      - referencing==0.37.0
      - regex==2025.11.3
      - requests==2.32.5
      - resemble-perth==1.0.1
      - rfc3986==1.5.0
      - rich==14.2.0
      - rpds-py==0.30.0
      - ruff==0.14.10
      - s3tokenizer==0.3.0
      - safehttpx==0.1.7
      - safetensors==0.5.3
      - scikit-learn==1.8.0
      - scipy==1.16.3
      - segments==2.3.0
      - semantic-version==2.10.0
      - shellingham==1.5.4
      - six==1.17.0
      - smart-open==7.5.0
      - soundfile==0.13.1
      - soxr==1.0.0
      - spacy==3.8.11
      - spacy-curated-transformers==0.3.1
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - spacy-pkuseg==1.0.1
      - srsly==2.5.2
      - starlette==0.50.0
      - sympy==1.13.1
      - termcolor==3.2.0
      - thinc==8.3.10
      - threadpoolctl==3.6.0
      - tokenizers==0.20.3
      - tomlkit==0.13.3
      - torch==2.6.0
      - torchaudio==2.6.0
      - tqdm==4.67.1
      - transformers==4.46.3
      - typer==0.21.0
      - typer-slim==0.21.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - uritemplate==4.2.0
      - urllib3==2.6.2
      - uvicorn==0.40.0
      - virtualenv==20.35.4
      - wasabi==1.1.3
      - weasel==0.4.3
      - websockets==15.0.1
      - wrapt==2.0.1
      - zipp==3.23.0
prefix: /opt/homebrew/Caskroom/miniconda/base/envs/tts_app
